name: Crear Archivo y Saludar

on:
  push:
    branches:
      - 'Dev'

jobs:
  create_file_and_greet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Crear Archivo y Saludar
      run: |
        echo "Hola Mundo" > nuevo_archivo.txt
        git add nuevo_archivo.txt
        git commit -m "Crear archivo y saludar"
        
